name: Publish

on:
  push:
    tags:
      - '*.*.*'

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v6

      - name: Create package
        run: make package

      - name: Create GitHub release
        uses: softprops/action-gh-release@v3
        with:
          name: ${{ github.ref_name }}
          generate_release_notes: true
          files: skills.tar.gz
          fail_on_unmatched_files: true
          draft: false
          prerelease: ${{ contains(github.ref_name, '-rc') || contains(github.ref_name, '-beta') }}
